src/Silex/Application.php
tests/Silex/Tests/MiddlewareTest.php

Handling responses returned from after middlewares is already implemented in the middleware event listener, but was missing from the application's after method. https://github.com/naderman/Silex/blob/1.2/src/Silex/EventListener/MiddlewareListener.php#L79

Allow global after middlewares to return responses like route specific ones

---

tests/Silex/Tests/Application/SecurityTraitTest.php

Additional tests to cover: 
- Empty token: https://github.com/silexphp/Silex/blob/1.2/src/Silex/Application/SecurityTrait.php#L33-35
- Invalid user: https://github.com/silexphp/Silex/blob/1.2/src/Silex/Application/SecurityTrait.php#L37-39

Improve code coverage of SecurityTrait

---

src/Silex/Application.php
src/Silex/Provider/KernelServiceProvider.php

This introduces a new KernelServiceProvider that is auto registered
by Silex\Application.
The main reason for including this is to remove the ugly
"dispatcher_class" hack we used to have. But since we introduced a
seperate interface for listeners to use for subscribing we can just have
a nice normal service.

Introduce KernelServiceProvider in order to remove "hacks"

---

README.rst

Alternative to #1075.
I've kept the syntax using phpunit.phar as it must be the most portable way to run PHPUnit (like it is for Composer).

[1.2] Fix doc about running unit tests

---

doc/changelog.rst
doc/services.rst
doc/testing.rst
src/Silex/ExceptionHandler.php
tests/Silex/Tests/ApplicationTest.php
tests/Silex/Tests/ExceptionHandlerTest.php
tests/Silex/Tests/Provider/RememberMeServiceProviderTest.php
tests/Silex/Tests/Provider/SessionServiceProviderTest.php
tests/Silex/Tests/RouterTest.php

replaces #1141
Note that 2.7 beta1 won't work because symfony/symfony#14313 was merged after the release.

fixed compatibility with 2.7

---

src/Silex/Controller.php
tests/Silex/Tests/ControllerTest.php

(As requested, this is #1154 rebased against 1.3.)
At present, mounted controllers can get weird route names. For instance, let's say you have this controller definition:
$otherController = $app['controllers_factory'];
$otherController->get('/{name}', function (Request $request, $name) use ($app) {
return new Response("Goodbye $name!\n", 200, ['Content-Type' => 'text/plain']);
});
$app->mount('/goodbye', $otherController);
The generated route name in this case will be `_goodbyeGET_name`, which technically contains everything, but is ugly.
With this PR, the route name will change to `GET_goodbye_name`, which is considerably easier to parse when debugging.

Have `Controller::generateRouteName()` always put the method first.

---

doc/providers/doctrine.rst

MySQL's `utf8` character set is a little broken, and does not cover 4-byte UTF-8 characters. In most cases it will quietly truncate the string whenever it sees one, saving incomplete text data.  
In  5.5.3 they introduced `utf8mb4` to fix this inconsistency, and given that it's been 5 years, it's probably safe to encourage people to use it. If their MySQL installation is older, it should be easy for them to find the distinctive string and change it back to `utf8`, and for a new project.
Additional details can be found in the equivalent [pull-request for Symfony-2](https://github.com/symfony/symfony-docs/pull/5100).

Changed Doctrine page to use utf8mb4 as sample

---

src/Silex/Application/SecurityTrait.php
src/Silex/Provider/SecurityServiceProvider.php

In Silex 1.3, it's "harder" to get the user from the security layer as the `security` service has been deprecated. The code is already available in the security trait, but if you are not using it, you need to use a somewhat "complex" expression in templates to access it (see #1152)
This PR moves the code from the trait to the security service to make it available to everyone.
One question though: can we deprecate the trait `user()` function? It is not useful anymore after this PR.

Easier user access

---

src/Silex/Provider/SessionServiceProvider.php

replaces #934 by making possible to override the default bags, but more importantly, it removes the storage definition from the inside of the session one to the outside.

refactored the session provider

---

src/Silex/ControllerCollection.php
tests/Silex/Tests/ControllerCollectionTest.php

In 4e6031e2, I added a safeguard by mistake which makes configuration on nested collection not possible. This fixes this issue but only for the upcoming 2.0 branch as it might break BC.
fixes #1017, #1100, and #1081

cascade route configuration for embedded route collection

---

src/Silex/Application.php
src/Silex/ControllerCollection.php
tests/Silex/Tests/ApplicationTest.php
tests/Silex/Tests/ControllerCollectionTest.php

Note: replaces #1174, which was targeting a wrong branch (and where I messed a bit with the commits ;)).
--
The aim of this PR is to allow developpers to subclass `Symfony\Component\Routing\RouteCollection` to change some of its behavior.
In most of my Silex apps, I figured I don't want the Symfony's `RouteCollection` regular behavior where if you define two routes with the same name (bad copy-paste for instance), the first route added simply gets overriden by the second. Instead, I would like to be able to throw an Exception if that happens. So I've written [a tiny subclass of RouteCollection](https://github.com/lschricke/symfony-strict-route-collection), but to be able to use it (through [a service provider like this](https://github.com/lschricke/silex-strict-route-collection-service-pro …

Added factory for RouteCollection, makes subclassing of RouteCollection possible.

---

src/Silex/Application.php
src/Silex/ControllerCollection.php

I propose to remove the `flush()` prefix argument as I don't see any use case. I think it was there because the method is recursive, but that's leaking an implementation detail. Passing a prefix was not documented.

removed flush() argument

---

src/Silex/ControllerCollection.php

`doFlush` returns the same `RouteCollection` instance now, so there's no need to add the sub-collection routes to itself.

Remove duplicate call to add collection

---

src/Silex/Provider/TwigServiceProvider.php
tests/Silex/Tests/Provider/TwigServiceProviderTest.php

form.csrf_provider is refactored to csrf.token_manager.

Fix bug: TwigServiceProvider is broken if FormServiceProvider is registered

---

src/Silex/Provider/MonologServiceProvider.php
src/Silex/Provider/TranslationServiceProvider.php
src/Silex/Provider/TwigServiceProvider.php

This lets everything work with Silex which lacks a request_stack, and I also made a couple changes to the monolog bootstrapping so it's easier to just override the monolog.handler OR monolog.handlers, before you kinda had to redefine both to customize anything.
I also moved the monolog.handler.debug out of the GroupHandler which makes more sense I think because if it is in the group then it falls under the not_found_activation_strategy and therefore even in debug mode you won't get any logs unless you get an error-level record.

Remove mandatory dependency on request_stack and some monolog improvements

---

src/Silex/WebTestCase.php

`Silex/WebTestCase` have a requirement for `symfony/browser-kit`.
This PR give instructions to the developer when PHPUnit is run and this dependency is missing.
Before:
```
PHP Fatal error:  Class 'Symfony\Component\BrowserKit\Client' not found in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Client.php on line 32
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:547
PHP   3. PHPUnit_TextUI_Command->run() phar:///usr/bin/phpunit/phar/phpunit/TextUI/Command.php:100
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///usr/bin/phpunit/phar/phpunit/TextUI/Command.php:148
PHP   5. PHPUnit_Framework_TestSuite->run() phar:///usr/bin/phpunit/phar/phpunit/TextUI/TestRunner.php:432
PHP   6. PHPUnit_Framework_TestCase->run() …
```

Add hint to install browser-kit to use WebTestCase

---

doc/providers/form.rst

In order to include people who do not fit into the gender binary, gender fields really should be a free-form text field. As such, this patch changes the `choices` example to use a billing plan instead.
* http://gender.wikia.com/wiki/Non-binary
* https://en.wikipedia.org/wiki/Genderqueer
* https://modelviewculture.com/pieces/the-argument-for-free-form-input
* https://www.facebook.com/

Replace binary gender examples with something that is actually single-choice

---

.travis.yml

SYMFONY_DEPS_VERSION=3 was never evaluated correctly as the before_scripts are comparing with 3.0
The tests were still installing 3.0, as minimumStability=dev, but maybe it is nice fixing that.

Fix env variable in travis.yaml

---

src/Silex/Provider/TwigServiceProvider.php
tests/Silex/Tests/Provider/TwigServiceProviderTest.php

Trivial fix for #1331, with test.

Fixing TwigServiceProvider when used with FormServiceProvider but without CsrfServiceProvider

---

doc/providers/security.rst

update documentation hashed password to match the default password encoder because the old hash is not valid with the bcrypt encoder
see #1320

encode documentation exemple password with password_hash

---

doc/providers/form.rst

Ref: https://github.com/silexphp/Silex/issues/1302
How is pre-Symfony3 documentation handled?  Is that a separate page or should notes on pre-Symfony3 usage be included on this page?

Address bc changes from Symfony 2.8 to Symfony 3

---

doc/web_servers.rst

Apache config is not my thing, so this might not be correct. However, what I can tell is that it does not work with the slash for me, and that it does without the slash.

Remove slash from FallbackResource

---

src/Silex/Api/BootableProviderInterface.php

`BootableServiceProvider` has an outdated description.  This PR brings the comment into line with the rest of the interfaces in `Silex\Api`

Clarify purpose of BootableServiceProvider

---

src/Silex/Provider/SessionServiceProvider.php
tests/Silex/Tests/Provider/SessionServiceProviderTest.php

The service provider was registering the wrong parameters
to the session listener instead of the actual session class
This fixes #1342 
Signed-off-by: RJ Garcia <rj@bighead.net>

Fixed Session Service Provider registry

---

doc/providers/service_controller.rst
src/Silex/CallbackResolver.php
tests/Silex/Tests/CallbackResolverTest.php

Added the ability for the callback resolver to support any callable instead
of just the object and method callable type.
An alternate implementation to this would be to update the CallbackResolver to use an interface, then keep the old CallbackResolver as is and just add a new implementation that you can change if you'd like. I'd probably prefer to do the interface, but depends on what people think.
This fixes #1327 
Signed-off-by: RJ Garcia <rj@bighead.net>

Added support for callables in CallbackResolver

---

doc/organizing_controllers.rst
src/Silex/Application.php
src/Silex/ControllerCollection.php
src/Silex/Provider/RoutingServiceProvider.php
tests/Silex/Tests/ApplicationTest.php
tests/Silex/Tests/ControllerCollectionTest.php
tests/Silex/Tests/Provider/RoutingServiceProviderTest.php

- Added the ability to pass callables into the controller collection
mount method.
- Updated documentation to show usage of new callables in mount and
recursive mounting.
- Added appropriate tests
This addresses #1262 and #1290 
Signed-off-by: RJ Garcia <rj@bighead.net>

Allowing callables for mount

---

doc/organizing_controllers.rst

Updated the var name in the organizing controllers documenation
in order be consistent with the variable naming throughout the
code sample.
Signed-off-by: RJ Garcia <rj@bighead.net>

Fixed var name in organizing controllers

---

doc/providers/monolog.rst
src/Silex/Provider/MonologServiceProvider.php

The monolog error handler can now be disabled by setting the value of the new `monolog.use_error_handler` parameter to false (since it was added in  a53ce5902983493c53eea61f6cf1e304c0aa6409 it was always enabled).
The error handler is disabled by default when the application `debug` parameter is set to true, to ensure it won't silence exceptions and/or errors. 
Without the flag, an uncaught exception thrown during boot on `master` will just result in a white page, even when using `debug` and `error_reporting` (because the error handler calls `exit` after logging exceptions).

Adding a flag to disable the Monolog error handler

---

README.rst

Silex 2 has been released yesterday so `@dev` should be removed from the composer version string.

Fix installation instruction in readme

---

src/Silex/Provider/Routing/RedirectableUrlMatcher.php
tests/Silex/Tests/ApplicationTest.php

That was fixed in symfony/symfony#15392 (so before 2.8.0).

removed obsolete code (fixed in Symfony 2.3.32)

---

doc/providers/asset.rst

Add Symfony Twig Brigde installation in asset doc, I have the following error otherwise : `Unknown "asset" function`
Made it clearer that twig-bridge is required.

Add Symfony Twig Brigde installation in asset doc

---

doc/providers/monolog.rst
tests/Silex/Tests/Provider/MonologServiceProviderTest.php

This PR:
- adds a test for the `monolog.exception.logger_filter` configuration option for the MonologServiceProvider
- updates the description stating it is not a filter, but a mapping function from exception to error level

Test/Explain monolog.exception.logger_filter

---

src/Silex/Provider/TwigServiceProvider.php

Currently `TwigServiceProvider ` sets `$app['twig.app_variable']` to be function that has a dependency on classes that are not required by Silex. This will fail if the user then calls that function. This happens for example when the [silex-pimple-dumper](https://github.com/Sorien/silex-pimple-dumper) maps over the app and tries to dump it's content. 
This PR fixes that by moving this in the `class_exists('Symfony\Bridge\Twig\Extension\RoutingExtension')` check. 
I've also added comment because at first it wasn't clear for me that this check for the `RoutingExtension` was the check for the whole Twig bridge. Please feel free to rebase and remove it it you don't like it or I misinterpreted it.
Keep up the good work! 👍

Move setting $app['twig.app_variable'] after 'Symfony\Bridge\Twig' check

---

doc/services.rst

There was an extra space breaking the URL formatting

RequestStack link in Services documentation is broken

---

src/Silex/Provider/FormServiceProvider.php
tests/Silex/Tests/Provider/FormServiceProviderTest.php

Closes https://github.com/symfony/symfony/issues/21199.
This PR makes the form configuration aligned with the symfony full stack, see https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/FrameworkBundle/Resources/config/form.xml#L11-L29.

Added the FormRegistry as a service to enable the extension point

---

.travis.yml
composer.json

This will fix the Travis build issues with PHP 7.
I upped the `symfony/phpunit-bridge` version requirement so we can use the `simple-phpunit` script that was added in 3.2.0, and updated the `script` config value.
While I was at it, I also added PHP 7.1 to the matrix (hopefully it's ok to do this in the same PR).

Use the simple-phpunit script in Travis and add PHP 7.1

---

tests/Silex/Tests/Provider/AssetServiceProviderTest.php

The test broke when symfony/symfony#22528 got merged. 
I added one check without the starting slash (the returned path should be relative to `base_path`) and modified the expectation of the check with the starting slash (the returned path should not be relative).
```
There was 1 failure:
1) Silex\Tests\Provider\AssetServiceProviderTest::testGenerateAssetUrl
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/whatever-makes-sense/foo.css?css2'
+'/foo.css?css2'
```

Fix AssetServiceProviderTest::testGenerateAssetUrl

---

src/Silex/Provider/TwigServiceProvider.php

Fixes the deprecation triggered when instantiating `FormExtension` twig-bridge with 3.2+.
I check for the existence of `Symfony\Bridge\Twig\Extension\HttpKernelRuntime` to determine if we're using 3.2 as it was added in 3.2.0-beta1.

Fix deprecation notice with symfony/twig-bridge 3.2+ in TwigServiceProvider

---

doc/providers/twig.rst
src/Silex/Provider/TwigServiceProvider.php
tests/Silex/Tests/Provider/TwigServiceProviderTest.php

This adds the following parameters to configure `Twig_Extension_Core`:
- `twig.date.format` (default `date` format)
- `twig.date.interval_format` (default `date` format for intervals)
- `twig.date.timezone` (default timezone)
- `twig.number_format.decimals` (default number of decimals for `number_format`)
- `twig.number_format.decimal_point` (default decimals separator for `number_format`)
- `twig.number_format.thousands_separator` (default thousands separator for `number_format`)

Added parameters to configure the Twig core extension behavior

---

composer.json
doc/providers/twig.rst
src/Silex/Provider/HttpKernelServiceProvider.php
src/Silex/Provider/TwigServiceProvider.php
tests/Silex/Tests/ApplicationTest.php
tests/Silex/Tests/Provider/TwigServiceProviderTest.php

I made the necessary changes to support the new WebLink component:
- `HttpKernelServiceProvider` registers the `AddLinkHeaderListener` if the component is available
- `TwigServiceProvider` adds the `WebLinkExtension` if the component and the Twig bridge are available
- Both changes are tested
- The documentation has been amended (the link to the Symfony website doesn't work as 3.3 hasn't been released yet but I believe it's the good URL)

Added WebLink component integration

---

doc/services.rst

The docs state that "protected closures do not get access to the container", but this is somewhat misleading (it confused me for a quite some time). It's true that protected closures are not passed the container as a function argument, but they can access the container via `use ($app)`.

Clarify documentations around protected closures.

---

doc/providers/security.rst

The `user` method hasn't been part of the security
trait since 7052d97 over 2 years ago.

Remove outdated example code from documentation

---

doc/providers/csrf.rst

The csrf.token_manager is an implementation of CsrfTokenManagerInterface
Fix the label and link to the reference
Update Usage section to include creation of a new token

Docs: Update interface reference for csrf.token_manager

---

src/Silex/Provider/Routing/RedirectableUrlMatcher.php

Symfony's HttpUtils's checkRequestPath() expects RedirectableUrlMatcher to return an array with '_route'. This throws a notice `Undefined index: _route`:
```
$coll = new RouteCollection();
$coll->add('foo', new Route('/foo', array(), array(), array(), '', array('https')));
$matcher = new RedirectableUrlMatcher($coll, new RequestContext());
$httpUtils = new HttpUtils(null, $matcher);
$request = Request::create('http://example.com/foo');
$httpUtils->checkRequestPath($request, 'foo');
```
It's an issue with my app although I haven't yet taken the time to make a simplified app to show the issue besides the above.

RedirectableUrlMatcher needs to return a proper array with the _route parameter

---

src/Silex/Provider/HttpFragmentServiceProvider.php

Trying to use twig functions "controller" and "render_esi" like [Symfony esi reference](http://symfony.com/doc/current/http_cache/esi.html) , i've noticed the following error:
An exception has been thrown during the rendering of a template ("You must use a URI when using the ESI rendering strategy or set a URL signer.").
It's the lack of a UriSigner on the constructor.

Error using EsiFragment with provider and twig functions

---

doc/providers/serializer.rst

This updates the documentation explaining how to setup any cache that implements the Doctrine interface. As the Symfony documentation don't clearly shows how to do this, I intend to add it here.

Update documentation to add cache explaination

---

src/Silex/Provider/TranslationServiceProvider.php
tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php

`translator.resource` is wrongly registered as a protected closure in `TranslationServiceProvider` (it was originally added correctly in dd27038, but changed in 48a3fdc).
That makes a test fail with Pimple 3.2.1 due to the silexphp/Pimple#190 fix as `translator.resource` can't be extended.

Fixed translator.resources definition

---

tests/Silex/Tests/ControllerResolverTest.php
tests/Silex/Tests/ServiceControllerResolverTest.php

Fixes deprecation notices/failures due to the deprecation of `ControllerResolverInterface::getArguments()`:
1. `Silex\ControllerResolver` [is not used by Silex](https://github.com/silexphp/Silex/blob/master/src/Silex/Provider/HttpKernelServiceProvider.php#L37) when using HttpKernel >= 3.1.0, so I skipped the only test present in `ControllerResolverTest` with recent versions, as it failed when testing against HttpKernel v4  (master).
2. `ServiceControllerResolverTest::testShouldDelegateGetArguments()` only asserts that the deprecated method is called, so added a `@group legacy` to handle the notice, and skipped the test with v4 to prevent a warning (PHPUnit complains when you mock a non-existent method).

Handle the ControllerResolverInterface::getArguments deprecation in tests

---

src/Silex/Provider/SwiftmailerServiceProvider.php

Adding stream_context_options to the $app['swiftmailer.options']

Swiftmailer SSL stream_context_options cannot be set #1582 :

---

tests/Silex/Tests/ApplicationTest.php
tests/Silex/Tests/ControllerCollectionTest.php
tests/Silex/Tests/Provider/DoctrineServiceProviderTest.php
tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php
tests/Silex/Tests/StreamTest.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertFalse` instead of strict comparison with `false` keyword;
- `assertArrayHasKey` instead of `isset` function.

Refactoring tests

---

src/Silex/Provider/TwigServiceProvider.php

Hello,
Recently, I had to use Symfony project's pieces of code in a Silex project, extending parent templates through submodules. These submodules, on which I had no control, used namespaced templates in their Twig files, such as:
```twig
{% import "@FooModule/macros.html.twig" as macros %}
```
____
Silex cannot resolve namespaces by default, since you have to register paths as following:
```php
$app->register(new TwigServiceProvider(), array(
'twig.path' => [
'../app/Resources/views',
'../common/foo-module/Resources/views'
]
));
```
What I had to do in order to get it working in the project was to "hack" the `\Twig_Loader_Filesystem` class (*PHP 7+*):
```php
$paths = [
'../app/Resources/views',
'FooModule' => '../common/foo-module/Resources/views',
];
$app->register(new …
```

Namespaces for Twig paths

---

.travis.yml
composer.json
tests/Silex/Tests/ControllerCollectionTest.php
tests/Silex/Tests/Provider/FormServiceProviderTest.php
tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php

This PR does the following:
* dropped support for non-supported Symfony versions
* dropped support for HHVM
* removed the "dev" minimum stability in `composer.json`
* changed tests to run on stable versions of Symfony (instead of dev)
* optimized PHPUnit cache
* added tests for Symfony 3.4
* fixed risky tests

Removed tests for obsolete Symfony versions, remove HHVM support

---

doc/providers/twig.rst

global.flashes is available from symfony 3.3, I added it.
https://symfony.com/blog/new-in-symfony-3-3-improved-flash-messages

Add a description of global.flashes

---

src/Silex/Provider/SecurityServiceProvider.php

Fixes #1568.
The `'context'` parameter is defaulting to the `'name'` parameter, but then it wasn't used properly below.

Fix Security provider context usage

---

doc/usage.rst
src/Silex/ExceptionListenerWrapper.php

Closes #1450.
Prior and related PRs and issues:
- https://github.com/symfony/symfony/pull/19822
- https://github.com/symfony/symfony-docs/commit/5f0becf3233238a9d96cba39f3146a0e7ae03763
- https://github.com/symfony/symfony-docs/pull/9336

Allow setting custom status code on exception response

---

doc/providers/asset.rst
doc/providers/csrf.rst
doc/providers/monolog.rst
doc/providers/routing.rst
doc/providers/security.rst
doc/providers/session.rst
doc/providers/translation.rst
doc/providers/validator.rst
src/Silex/Provider/SessionServiceProvider.php

This documents all parameter options to providers which were missing from the documentation.

Sync provider parameters in docs

---

src/Silex/Provider/TwigServiceProvider.php

Fixes #1448.
This fixes an incompatibility with Symfony Twig bridge prior to 3.2.
The HttpKernelRuntime was introduced in https://github.com/silexphp/Silex/commit/72d7746ec216da230221c19aa6e3092b55596070.
It included checks whether the class exists, but not in the Twig runtimes list.

Check for HttpKernelRuntime before using it in Twig runtimes

---

doc/providers/security.rst
src/Silex/Provider/SecurityServiceProvider.php
tests/Silex/Tests/Provider/SecurityServiceProviderTest.php

Allow defining users provider as a service ID

---

src/Silex/Provider/SecurityServiceProvider.php
tests/Silex/Tests/Provider/SecurityServiceProviderTest.php

Follow-up to https://github.com/silexphp/Silex/pull/1611 and https://github.com/silexphp/Silex/pull/1217.
Fixes https://github.com/silexphp/Silex/issues/1630.

Treat user provider as a service in security service provider

---

tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php

Since Pimple 2.x there is no need to re-assign the result from `extend()` call to the same key. Pimple already does that.

Simplify extend call
