silexphp/Silex

- src/Silex/Provider/DoctrineServiceProvider.php
See https://github.com/silexphp/Silex-Providers/commit/d0f1432d395d5be4d716d3c2c23fd297b815bb4f#commitcomment-9229361
> Remove a port from the default db options

- doc/usage.rst
Update "Error Handlers" part in usage.rst because of https://github.com/silexphp/Silex/commit/e96f9be8fda96193313bb655d63b061d6d4d7c4d#diff-9460b640f6466d5890f37f7caf262024R52
> Update "Error Handlers" part in usage.rst

- src/Silex/Provider/SecurityServiceProvider.php
> fixed compatibility with Symfony 2.6

- src/Silex/ControllerCollection.php
- src/Silex/EventListener/LogListener.php
- src/Silex/ExceptionListenerWrapper.php
- src/Silex/Provider/SerializerServiceProvider.php
- src/Silex/RedirectableUrlMatcher.php
- tests/Silex/Tests/CallbackResolverTest.php
- tests/Silex/Tests/CallbackServicesTest.php
- tests/Silex/Tests/ControllerTest.php
- tests/Silex/Tests/LazyUrlMatcherTest.php
- tests/Silex/Tests/Provider/MonologServiceProviderTest.php
> PHPDocs cleans ups

- src/Silex/Provider/SerializerServiceProvider.php
- tests/Silex/Tests/Application/UrlGeneratorTraitTest.php
- tests/Silex/Tests/LazyRequestMatcherTest.php
- tests/Silex/Tests/Provider/TwigServiceProviderTest.php
Remove some stuff that doesn't apply anymore for master and a little typo.
> Clean ups on master

- doc/usage.rst
- src/Silex/Application.php
- src/Silex/ViewListenerWrapper.php
- tests/Silex/Tests/ApplicationTest.php
Previously #1062 and #863
TODO
> View Listener

- doc/providers/swiftmailer.rst
- src/Silex/Provider/SwiftmailerServiceProvider.php
> added sender_address to switfmailer provider

- src/Silex/WebTestCase.php
replacement of https://github.com/silexphp/Silex/pull/1193
(could not reopen that one because of a forced push)
> PHPDocs Application -> HttpKernelInterface

- doc/providers/security.rst
> updated the docs to show how to restrict a firewall by more than just the URL

- doc/providers/validator.rst
- src/Silex/ConstraintValidatorFactory.php
- src/Silex/Provider/SecurityServiceProvider.php
- src/Silex/Provider/ValidatorServiceProvider.php
- tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php
> added support for Symfony ConstraintValidatorFactory

- doc/changelog.rst
- doc/cookbook/form_no_csrf.rst
- doc/providers/csrf.rst
- doc/providers/form.rst
- doc/providers/serializer.rst
- src/Silex/Provider/CsrfServiceProvider.php
- src/Silex/Provider/FormServiceProvider.php
- tests/Silex/Tests/Provider/FormServiceProviderTest.php
- tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php
> added a CSRF service provider

- doc/changelog.rst
- doc/providers/twig.rst
- src/Silex/Provider/TwigServiceProvider.php
- tests/Silex/Tests/Provider/TwigServiceProviderTest.php
That's more consistent with Symfony.
> changed the app variable in Twig to be an instance of Symfony AppVariable

- src/Silex/Provider/MonologServiceProvider.php
- tests/Silex/Tests/Application/MonologTraitTest.php
- tests/Silex/Tests/Provider/MonologServiceProviderTest.php
@Seldaek If you can have a quick look, that would be much appreciated :)
> updated the Monolog provider to use the newest features of Monolog and the Symfony bridge

- src/Silex/Provider/SwiftmailerServiceProvider.php
> Verify that the spool is enabled and an actual spool before flushing it

- doc/changelog.rst
- doc/providers/translation.rst
- doc/providers/twig.rst
- src/Silex/Provider/TwigServiceProvider.php
- tests/Silex/Tests/Provider/TwigServiceProviderTest.php
> reverted app Twig variable change, introduced a new global one instead

- src/Silex/Application.php
- src/Silex/EventListener/LocaleListener.php
- src/Silex/Provider/HttpFragmentServiceProvider.php
Thanks @nicolas-grekas, that's ugly as I anticipated :(
> fixed deprecation notices

- doc/changelog.rst
- src/Silex/Provider/FormServiceProvider.php
- src/Silex/Provider/TranslationServiceProvider.php
- src/Silex/Provider/ValidatorServiceProvider.php
- tests/Silex/Tests/Provider/ValidatorServiceProviderTest.php
> fixed translation registration for the validators

- src/Silex/Application/FormTrait.php
Form FQCN are introduced with symfony 2.8.
> Fix comment about symfony version

- README.rst
> [README] Fixed the minimal PHP version

- doc/providers/security.rst
- src/Silex/Provider/SecurityServiceProvider.php
- tests/Silex/Tests/Application/SecurityTraitTest.php
- tests/Silex/Tests/Provider/RememberMeServiceProviderTest.php
- tests/Silex/Tests/Provider/SecurityServiceProviderTest.php
- tests/Silex/Tests/Route/SecurityTraitTest.php
Based on work of @mvanbaak (https://github.com/silexphp/Silex/pull/1316) with applied comments from @mathroc and fixed tests.
> Use BCrypt by default as encoder #1312

- composer.json
- doc/changelog.rst
- doc/usage.rst
- src/Silex/Controller.php
- src/Silex/ControllerCollection.php
- src/Silex/Route.php
- tests/Silex/Tests/ControllerCollectionTest.php
- tests/Silex/Tests/RouterTest.php
> added route conditions

- doc/providers/swiftmailer.rst
- src/Silex/Provider/SwiftmailerServiceProvider.php
add supports for swiftmailer.delivery_addresses & swiftmailer.delivery_whitelist
> mailer delivery address

- doc/providers/csrf.rst
Replace Serializer Component to Security CSRF Component in documentation
> fix typo in doc

- src/Silex/AppArgumentValueResolver.php
- tests/Silex/Tests/ApplicationTest.php
- tests/Silex/Tests/Fixtures/Php7Controller.php
> Fix PHP7 type hint on controllers

- doc/cookbook/guard_authentication.rst
see http://php.net/manual/en/function.strpos.php
> Fix invalid parameters order

- doc/cookbook/guard_authentication.rst
Add missing space in Guard Authentication doc
> Small typo fix

- src/Silex/Provider/MonologServiceProvider.php
Related to https://github.com/symfony/symfony/pull/20416
> Use DebugProcessor instead of DebugHandler when available in MonologServiceProvider

- doc/providers/swiftmailer.rst
- src/Silex/Provider/SwiftmailerServiceProvider.php
- tests/Silex/Tests/Provider/SpoolStub.php
- tests/Silex/Tests/Provider/SwiftmailerServiceProviderTest.php
This patch makes it easier to register SwiftMailer plugins.
> Make it easier to register SwiftMailer plugins

- doc/cookbook/validator_yaml.rst
Change the ClassMetadataFactory to LazyLoadingMetadataFactory because it is deprecated in last version.
> Change the ClassMetadataFactory

- doc/cookbook/multiple_loggers.rst
- doc/cookbook/session_storage.rst
- doc/providers.rst
- doc/providers/form.rst
Hi all!
I've made a few minor changes to the docs ~to get those back into shape.
However I could use help finishing the `routing.rst`, this describes the `RoutingServiceProvider`.
The provider is powerful and awesome, but I struggle getting any good copy in there.
So if you have time please help out :)~
> Update the documentation

- doc/providers/session.rst
Expand the documentation to explain how to use different session providers.
> Update session.rst to explain handlers

- doc/organizing_controllers.rst
Hi,
I found a minor typo in this particular file. Kindly please check it and merge the pull request if you find it valid.
Thanks!
> A minor typo

- src/Silex/Provider/RoutingServiceProvider.php
> Updated for RouterListener from symfony/http-kernel v3.4+

- doc/changelog.rst
- src/Silex/Provider/SecurityServiceProvider.php
- tests/Silex/Tests/Provider/SecurityServiceProviderTest.php
> Fix validator integration into the security provider

- README.rst
This PR documents the new version constraints from #1607.
> Updated PHP compatibility information in README

- doc/providers/form.rst
> Remove typo

- src/Silex/Provider/MonologServiceProvider.php
- src/Silex/Provider/SessionServiceProvider.php
Follow up to 7bee6bfd6134f418a47188e62ce9e57fc82cd0ac
> Unify dispatcher usage in service providers

- README.rst
> Replace IRC with StackOverflow/GitHub

- src/Silex/Provider/TwigServiceProvider.php
Fixes https://github.com/silexphp/Silex/issues/1577
Alternative to #1616.
> Replace twig.options defaults every time

- doc/changelog.rst
- doc/providers/security.rst
- src/Silex/Provider/SecurityServiceProvider.php
Reverts https://github.com/silexphp/Silex/pull/1614.
Reopens https://github.com/silexphp/Silex/issues/1530.
See problems and discussed solutions in https://github.com/silexphp/Silex/pull/1619.
> Revert ServiceIteraror in Security provider voters

- README.rst
Despite some great work done in the last couple of months, nobody showed a strong motivation to take over this project.
I want to thank @hkdobrev for his hard work as he helped me lot in closing issues and fixing bugs. Silex is now compatible with Symfony 4 and that's going to help a lot in migrating projects.
I still strongly believe that Symfony 4 is a better alternative and that there is nothing unique anymore in Silex.
Forking is still an option if someone wants to take over of course.
> Remove help wanted text from README
